import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'
import { Building2, Users, Zap, TrendingUp } from 'lucide-react'

function Home() {
  const [gameName, setGameName] = useState('')
  const [playerName, setPlayerName] = useState('')
  const [companyName, setCompanyName] = useState('')
  const [loading, setLoading] = useState(false)
  const navigate = useNavigate()

  const createGame = async (e) => {
    e.preventDefault()
    setLoading(true)

    try {
      // Create game
      const gameRes = await axios.post('/api/game/create', {
        name: gameName || 'New Capital Clash',
        maxRounds: 8
      })

      const gameId = gameRes.data.game.id

      // Initialize board
      await axios.post(`/api/game/${gameId}/initialize-board`)

      // Join as player
      const playerRes = await axios.post('/api/player/join', {
        gameId,
        playerName: playerName || 'Player 1',
        companyName: companyName || 'My Company'
      })

      // Store player ID so we know they're in the game
      localStorage.setItem(`player_${gameId}`, playerRes.data.player.id)

      navigate(`/lobby/${gameId}`)
    } catch (error) {
      console.error('Error creating game:', error)
      alert('Failed to create game. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-8">
      {/* Hero Section */}
      <div className="text-center mb-12 space-y-6 animate-slide-up">
        <h1 className="text-6xl font-display font-bold neon-glow text-transparent bg-clip-text bg-gradient-to-r from-neon-blue via-neon-purple to-neon-pink">
          💼 CAPITAL CLASH
        </h1>
        <p className="text-2xl text-gray-300 font-light">
          Rise of the CEOs
        </p>
        <p className="text-lg text-gray-400 max-w-2xl">
          Compete to build the most valuable company empire in a living, AI-driven economy. 
          Every decision matters. Every round changes everything.
        </p>
      </div>

      {/* Feature Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12 w-full max-w-5xl">
        <div className="glass rounded-lg p-6 card-glow">
          <Building2 className="w-10 h-10 text-neon-blue mb-4" />
          <h3 className="text-xl font-semibold mb-2">AI-Powered World</h3>
          <p className="text-gray-400">Every game is unique with dynamic events and news generated by AI</p>
        </div>
        
        <div className="glass rounded-lg p-6 card-glow">
          <Users className="w-10 h-10 text-neon-purple mb-4" />
          <h3 className="text-xl font-semibold mb-2">Multiplayer Strategy</h3>
          <p className="text-gray-400">Compete with friends or AI in business simulations</p>
        </div>

        <div className="glass rounded-lg p-6 card-glow">
          <Zap className="w-10 h-10 text-neon-pink mb-4" />
          <h3 className="text-xl font-semibold mb-2">Real-Time Actions</h3>
          <p className="text-gray-400">Buy, sell, build, and trade in real-time across the city</p>
        </div>

        <div className="glass rounded-lg p-6 card-glow">
          <TrendingUp className="w-10 h-10 text-neon-blue mb-4" />
          <h3 className="text-xl font-semibold mb-2">Dynamic Economy</h3>
          <p className="text-gray-400">Watch the market rise and fall with AI-controlled events</p>
        </div>
      </div>

      {/* Create Game Form */}
      <div className="glass rounded-xl p-8 w-full max-w-2xl card-glow">
        <h2 className="text-3xl font-bold mb-6 text-center">Create New Game</h2>
        <form onSubmit={createGame} className="space-y-4">
          <div>
            <label className="block text-sm font-medium mb-2">Game Name (Optional)</label>
            <input
              type="text"
              value={gameName}
              onChange={(e) => setGameName(e.target.value)}
              placeholder="My Epic Battle"
              className="w-full px-4 py-3 rounded-lg"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-2">Your Name</label>
            <input
              type="text"
              value={playerName}
              onChange={(e) => setPlayerName(e.target.value)}
              placeholder="CEO Name"
              className="w-full px-4 py-3 rounded-lg"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-2">Company Name</label>
            <input
              type="text"
              value={companyName}
              onChange={(e) => setCompanyName(e.target.value)}
              placeholder="Acme Corp"
              className="w-full px-4 py-3 rounded-lg"
              required
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="btn-primary w-full py-4 rounded-lg font-semibold text-lg mt-6 disabled:opacity-50"
          >
            {loading ? 'Creating Game...' : '🎮 Start Game'}
          </button>
        </form>
      </div>

      {/* Footer */}
      <div className="mt-12 text-center text-gray-500 text-sm">
        <p>Powered by OpenAI GPT-4 • Built with React & Node.js</p>
      </div>
    </div>
  )
}

export default Home

