-- Capital Clash Database Schema

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Games Table
CREATE TABLE IF NOT EXISTS games (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'waiting', -- waiting, active, finished
    current_round INTEGER DEFAULT 1,
    max_rounds INTEGER DEFAULT 8,
    current_player_turn INTEGER DEFAULT 1,
    phase VARCHAR(50) DEFAULT 'player_phase', -- player_phase, ai_phase, round_end
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Players Table
CREATE TABLE IF NOT EXISTS players (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255),
    capital DECIMAL(15, 2) DEFAULT 1000000.00,
    reputation INTEGER DEFAULT 50,
    position INTEGER DEFAULT 1,
    is_human BOOLEAN DEFAULT true,
    ai_personality VARCHAR(50), -- ruthless_shark, chaotic_innovator, eco_warrior
    order_in_game INTEGER,
    status VARCHAR(50) DEFAULT 'active', -- active, eliminated
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(game_id, order_in_game)
);

-- Districts Table (Game Board Layout)
CREATE TABLE IF NOT EXISTS districts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL, -- tech_park, downtown, industrial, green_valley, luxury_mile, harborfront
    description TEXT,
    market_value DECIMAL(15, 2) DEFAULT 0,
    economic_condition VARCHAR(50) DEFAULT 'stable', -- booming, stable, recession, crisis
    order_on_board INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tiles Table (Individual Properties)
CREATE TABLE IF NOT EXISTS tiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    district_id UUID REFERENCES districts(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    owner_id UUID REFERENCES players(id) ON DELETE SET NULL,
    purchase_price DECIMAL(15, 2) NOT NULL,
    current_value DECIMAL(15, 2) NOT NULL,
    development_level INTEGER DEFAULT 0, -- 0 = empty, 1 = branch, 2 = main office, 3 = headquarters
    income_per_round DECIMAL(15, 2) DEFAULT 0,
    property_type VARCHAR(50), -- business, factory, shop, etc.
    order_in_district INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Companies Table (Businesses Players Can Create)
CREATE TABLE IF NOT EXISTS companies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    industry VARCHAR(50) NOT NULL, -- ai, retail, energy, manufacturing, entertainment
    valuation DECIMAL(15, 2) NOT NULL,
    revenue_per_round DECIMAL(15, 2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'active', -- active, bankrupt, acquired
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Player Actions Table (Action History)
CREATE TABLE IF NOT EXISTS player_actions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL,
    action_type VARCHAR(50) NOT NULL, -- buy_tile, sell_tile, build, invest, launch_company, etc.
    details JSONB,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI Events Table (Dynamic Events Generated by AI)
CREATE TABLE IF NOT EXISTS ai_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL,
    event_type VARCHAR(50) NOT NULL, -- market_crash, boom, regulation, crisis, bonus
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    affected_district_id UUID REFERENCES districts(id) ON DELETE CASCADE,
    affected_players UUID[],
    impact_data JSONB, -- {economy: +10, tech_park: -5, etc}
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- News Reports Table (AI-Generated News)
CREATE TABLE IF NOT EXISTS news_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL,
    headline VARCHAR(255) NOT NULL,
    story TEXT NOT NULL,
    player_impacts JSONB, -- {player_id: {capital: +50000, reputation: +2}}
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Market Conditions Table (Economy State)
CREATE TABLE IF NOT EXISTS market_conditions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL,
    condition_data JSONB NOT NULL, -- {tech_park: 120, downtown: 95, etc}
    overall_sentiment VARCHAR(50), -- bullish, stable, bearish, crisis
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    message_type VARCHAR(50) DEFAULT 'chat', -- chat, trade_request, action_announcement
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Trade Offers Table
CREATE TABLE IF NOT EXISTS trade_offers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    game_id UUID REFERENCES games(id) ON DELETE CASCADE,
    from_player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    to_player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    offer_type VARCHAR(50) NOT NULL, -- tile_trade, capital_trade, company_trade, action_trade
    offer_details JSONB NOT NULL,
    status VARCHAR(50) DEFAULT 'pending', -- pending, accepted, rejected, cancelled
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_players_game_id ON players(game_id);
CREATE INDEX IF NOT EXISTS idx_tiles_game_id ON tiles(game_id);
CREATE INDEX IF NOT EXISTS idx_tiles_owner_id ON tiles(owner_id);
CREATE INDEX IF NOT EXISTS idx_companies_game_id ON companies(game_id);
CREATE INDEX IF NOT EXISTS idx_companies_player_id ON companies(player_id);
CREATE INDEX IF NOT EXISTS idx_player_actions_game_id ON player_actions(game_id);
CREATE INDEX IF NOT EXISTS idx_player_actions_player_id ON player_actions(player_id);
CREATE INDEX IF NOT EXISTS idx_ai_events_game_id ON ai_events(game_id);
CREATE INDEX IF NOT EXISTS idx_news_reports_game_id ON news_reports(game_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_game_id ON chat_messages(game_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_player_id ON chat_messages(player_id);
CREATE INDEX IF NOT EXISTS idx_trade_offers_game_id ON trade_offers(game_id);
CREATE INDEX IF NOT EXISTS idx_trade_offers_from_player ON trade_offers(from_player_id);
CREATE INDEX IF NOT EXISTS idx_trade_offers_to_player ON trade_offers(to_player_id);

